apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lobsterai.fullname" . }}-service
  labels:
    {{- include "lobsterai.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lobsterai.fullname" . }}-runtime-orchestrator
  labels:
    {{- include "lobsterai.labels" . | nindent 4 }}
automountServiceAccountToken: false
