export const InventorySupport = { Ga: 'ga', PartialGa: 'partial-ga' } as const;
export const InventoryKind = { Route: 'route', Channel: 'channel' } as const;
export interface IpcGaInventoryEntry { readonly id:string; readonly legacyIpc:string; readonly direction:string; readonly kind:'route'|'channel'; readonly targets:readonly string[]; readonly sourceRef:string; readonly support:'ga'|'partial-ga'; }
export const IpcGaInventory = [
  {"id":"A-099","legacyIpc":"cowork:session:start","direction":"R→M","kind":"route","targets":["post_api_v1_sessions"],"sourceRef":"附录A:99","support":"ga"},
  {"id":"A-100","legacyIpc":"cowork:session:continue","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_turns"],"sourceRef":"附录A:100","support":"ga"},
  {"id":"A-101","legacyIpc":"cowork:session:stop","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_stop"],"sourceRef":"附录A:101","support":"ga"},
  {"id":"A-102","legacyIpc":"cowork:session:delete","direction":"R→M","kind":"route","targets":["delete_api_v1_sessions_id"],"sourceRef":"附录A:102","support":"ga"},
  {"id":"A-103","legacyIpc":"cowork:session:deleteBatch","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_batch_delete"],"sourceRef":"附录A:103","support":"ga"},
  {"id":"A-104","legacyIpc":"cowork:session:get","direction":"R→M","kind":"route","targets":["get_api_v1_sessions_id"],"sourceRef":"附录A:104","support":"ga"},
  {"id":"A-105","legacyIpc":"cowork:session:list","direction":"R→M","kind":"route","targets":["get_api_v1_sessions"],"sourceRef":"附录A:105","support":"ga"},
  {"id":"A-106","legacyIpc":"cowork:session:getMessages","direction":"R→M","kind":"route","targets":["get_api_v1_sessions_id_messages"],"sourceRef":"附录A:106","support":"ga"},
  {"id":"A-107","legacyIpc":"cowork:session:rename","direction":"R→M","kind":"route","targets":["patch_api_v1_sessions_id"],"sourceRef":"附录A:107","support":"ga"},
  {"id":"A-108","legacyIpc":"cowork:session:pin","direction":"R→M","kind":"route","targets":["patch_api_v1_sessions_id"],"sourceRef":"附录A:108","support":"ga"},
  {"id":"A-109","legacyIpc":"cowork:session:fork (CoworkIpcChannel.ForkSession)","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_fork"],"sourceRef":"附录A:109","support":"ga"},
  {"id":"A-110","legacyIpc":"cowork:session:remoteManaged","direction":"R→M","kind":"route","targets":["get_api_v1_sessions_id_managed"],"sourceRef":"附录A:110","support":"ga"},
  {"id":"A-111","legacyIpc":"cowork:session:contextUsage","direction":"R→M","kind":"route","targets":["get_api_v1_sessions_id_context_usage"],"sourceRef":"附录A:111","support":"ga"},
  {"id":"A-112","legacyIpc":"cowork:session:compactContext","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_compact_context"],"sourceRef":"附录A:112","support":"ga"},
  {"id":"A-113","legacyIpc":"cowork:session:markViewed (MarkSessionViewed)","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_viewed"],"sourceRef":"附录A:113","support":"ga"},
  {"id":"A-114","legacyIpc":"cowork:session:getMessageRailIndex","direction":"R→M","kind":"route","targets":["get_api_v1_sessions_id_rail_index"],"sourceRef":"附录A:114","support":"ga"},
  {"id":"A-115","legacyIpc":"cowork:session:captureImageChunk","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_result_image_chunks"],"sourceRef":"附录A:115","support":"ga"},
  {"id":"A-116","legacyIpc":"cowork:session:exportResultImage","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_exports_result_image"],"sourceRef":"附录A:116","support":"ga"},
  {"id":"A-117","legacyIpc":"cowork:session:saveResultImage","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_result_image_files"],"sourceRef":"附录A:117","support":"ga"},
  {"id":"A-118","legacyIpc":"cowork:session:exportText","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_exports_text"],"sourceRef":"附录A:118","support":"ga"},
  {"id":"A-119","legacyIpc":"get-recent-cwds","direction":"R→M","kind":"route","targets":["get_api_v1_workspaces_recent"],"sourceRef":"附录A:119","support":"ga"},
  {"id":"A-125","legacyIpc":"cowork:config:get","direction":"R→M","kind":"route","targets":["get_api_v1_cowork_config"],"sourceRef":"附录A:125","support":"ga"},
  {"id":"A-126","legacyIpc":"cowork:config:set","direction":"R→M","kind":"route","targets":["patch_api_v1_cowork_config"],"sourceRef":"附录A:126","support":"ga"},
  {"id":"A-127","legacyIpc":"cowork:memory:getStats","direction":"R→M","kind":"route","targets":["get_api_v1_cowork_memory_stats"],"sourceRef":"附录A:127","support":"ga"},
  {"id":"A-128","legacyIpc":"cowork:memory:listEntries","direction":"R→M","kind":"route","targets":["get_api_v1_cowork_memory_entries"],"sourceRef":"附录A:128","support":"ga"},
  {"id":"A-129","legacyIpc":"cowork:memory:createEntry","direction":"R→M","kind":"route","targets":["post_api_v1_cowork_memory_entries"],"sourceRef":"附录A:129","support":"ga"},
  {"id":"A-130","legacyIpc":"cowork:memory:updateEntry","direction":"R→M","kind":"route","targets":["patch_api_v1_cowork_memory_entries_id"],"sourceRef":"附录A:130","support":"ga"},
  {"id":"A-131","legacyIpc":"cowork:memory:deleteEntry","direction":"R→M","kind":"route","targets":["delete_api_v1_cowork_memory_entries_id"],"sourceRef":"附录A:131","support":"ga"},
  {"id":"A-132","legacyIpc":"cowork:bootstrap:read","direction":"R→M","kind":"route","targets":["get_api_v1_cowork_bootstrap"],"sourceRef":"附录A:132","support":"ga"},
  {"id":"A-133","legacyIpc":"cowork:bootstrap:write","direction":"R→M","kind":"route","targets":["put_api_v1_cowork_bootstrap"],"sourceRef":"附录A:133","support":"ga"},
  {"id":"A-134","legacyIpc":"cowork:dreaming:status","direction":"R→M","kind":"route","targets":["get_api_v1_cowork_dreaming_status"],"sourceRef":"附录A:134","support":"ga"},
  {"id":"A-135","legacyIpc":"cowork:dreaming:diary","direction":"R→M","kind":"route","targets":["get_api_v1_cowork_dreaming_diary"],"sourceRef":"附录A:135","support":"ga"},
  {"id":"A-141","legacyIpc":"cowork:permission:respond","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_permissions_requestId_respond"],"sourceRef":"附录A:141","support":"ga"},
  {"id":"A-142","legacyIpc":"cowork:media:cancel","direction":"R→M","kind":"route","targets":["post_api_v1_media_tasks_taskId_cancel"],"sourceRef":"附录A:142","support":"ga"},
  {"id":"A-143","legacyIpc":"media:getModels","direction":"R→M","kind":"route","targets":["get_api_v1_models","get_api_v1_media_models"],"sourceRef":"附录A:143","support":"ga"},
  {"id":"A-144","legacyIpc":"media:getTaskStatus","direction":"R→M","kind":"route","targets":["get_api_v1_media_tasks_taskId"],"sourceRef":"附录A:144","support":"ga"},
  {"id":"A-150","legacyIpc":"cowork:subagent:list (SubagentList)","direction":"R→M","kind":"route","targets":["get_api_v1_sessions_id_subagents"],"sourceRef":"附录A:150","support":"ga"},
  {"id":"A-151","legacyIpc":"cowork:subagent:delete (SubagentDelete)","direction":"R→M","kind":"route","targets":["delete_api_v1_subagents_runId"],"sourceRef":"附录A:151","support":"ga"},
  {"id":"A-152","legacyIpc":"cowork:subTask:history (SubTaskHistory)","direction":"R→M","kind":"route","targets":["get_api_v1_subagents_runId_messages"],"sourceRef":"附录A:152","support":"ga"},
  {"id":"A-160","legacyIpc":"agents:list","direction":"R→M","kind":"route","targets":["get_api_v1_agents"],"sourceRef":"附录A:160","support":"ga"},
  {"id":"A-161","legacyIpc":"agents:get","direction":"R→M","kind":"route","targets":["get_api_v1_agents_id"],"sourceRef":"附录A:161","support":"ga"},
  {"id":"A-162","legacyIpc":"agents:create","direction":"R→M","kind":"route","targets":["post_api_v1_agents"],"sourceRef":"附录A:162","support":"ga"},
  {"id":"A-163","legacyIpc":"agents:update","direction":"R→M","kind":"route","targets":["patch_api_v1_agents_id"],"sourceRef":"附录A:163","support":"ga"},
  {"id":"A-164","legacyIpc":"agents:delete","direction":"R→M","kind":"route","targets":["delete_api_v1_agents_id"],"sourceRef":"附录A:164","support":"ga"},
  {"id":"A-165","legacyIpc":"agents:presets","direction":"R→M","kind":"route","targets":["get_api_v1_agents_presets"],"sourceRef":"附录A:165","support":"ga"},
  {"id":"A-166","legacyIpc":"agents:presetTemplates","direction":"R→M","kind":"route","targets":["get_api_v1_agents_preset_templates"],"sourceRef":"附录A:166","support":"ga"},
  {"id":"A-167","legacyIpc":"agents:addPreset","direction":"R→M","kind":"route","targets":["post_api_v1_agents_presets_presetId_install"],"sourceRef":"附录A:167","support":"ga"},
  {"id":"A-175","legacyIpc":"artifact:watchFile","direction":"R→M","kind":"channel","targets":["subscribeEvent"],"sourceRef":"附录A:175","support":"ga"},
  {"id":"A-176","legacyIpc":"artifact:unwatchFile","direction":"R→M","kind":"channel","targets":["unsubscribeEvent"],"sourceRef":"附录A:176","support":"ga"},
  {"id":"A-177","legacyIpc":"artifact:createPreviewSession","direction":"R→M","kind":"route","targets":["post_api_v1_artifacts_artifactId_preview"],"sourceRef":"附录A:177","support":"ga"},
  {"id":"A-178","legacyIpc":"artifact:createOfficePreviewSession","direction":"R→M","kind":"route","targets":["post_api_v1_artifacts_artifactId_preview"],"sourceRef":"附录A:178","support":"ga"},
  {"id":"A-179","legacyIpc":"artifact:destroyPreviewSession","direction":"R→M","kind":"route","targets":["delete_api_v1_artifacts_preview_sessions_previewSessionId"],"sourceRef":"附录A:179","support":"ga"},
  {"id":"A-189","legacyIpc":"htmlShare:createFromHtmlFile","direction":"R→M","kind":"route","targets":["post_api_v1_html_shares"],"sourceRef":"附录A:189","support":"ga"},
  {"id":"A-190","legacyIpc":"htmlShare:updateFromHtmlFile","direction":"R→M","kind":"route","targets":["put_api_v1_html_shares_id"],"sourceRef":"附录A:190","support":"ga"},
  {"id":"A-191","legacyIpc":"htmlShare:getByHtmlFile","direction":"R→M","kind":"route","targets":["get_api_v1_html_shares"],"sourceRef":"附录A:191","support":"ga"},
  {"id":"A-192","legacyIpc":"htmlShare:createFromArtifactFile","direction":"R→M","kind":"route","targets":["post_api_v1_html_shares"],"sourceRef":"附录A:192","support":"ga"},
  {"id":"A-193","legacyIpc":"htmlShare:updateFromArtifactFile","direction":"R→M","kind":"route","targets":["put_api_v1_html_shares_id"],"sourceRef":"附录A:193","support":"ga"},
  {"id":"A-194","legacyIpc":"htmlShare:getByArtifactFile","direction":"R→M","kind":"route","targets":["get_api_v1_html_shares"],"sourceRef":"附录A:194","support":"ga"},
  {"id":"A-195","legacyIpc":"htmlShare:updateStatus","direction":"R→M","kind":"route","targets":["patch_api_v1_html_shares_id_status"],"sourceRef":"附录A:195","support":"ga"},
  {"id":"A-196","legacyIpc":"htmlShare:updateAccessMode","direction":"R→M","kind":"route","targets":["patch_api_v1_html_shares_id_access_mode"],"sourceRef":"附录A:196","support":"ga"},
  {"id":"A-197","legacyIpc":"htmlShare:disable","direction":"R→M","kind":"route","targets":["patch_api_v1_html_shares_id_status"],"sourceRef":"附录A:197","support":"ga"},
  {"id":"A-198","legacyIpc":"htmlShare:get","direction":"R→M","kind":"route","targets":["get_api_v1_html_shares_id"],"sourceRef":"附录A:198","support":"ga"},
  {"id":"A-206","legacyIpc":"shareDeployment:detectProjectCandidates","direction":"R→M","kind":"route","targets":["post_api_v1_share_deployments_candidates"],"sourceRef":"附录A:206","support":"partial-ga"},
  {"id":"A-207","legacyIpc":"shareDeployment:analyzeProjectDirectory","direction":"R→M","kind":"route","targets":["post_api_v1_share_deployments_analyze"],"sourceRef":"附录A:207","support":"partial-ga"},
  {"id":"A-208","legacyIpc":"shareDeployment:createNodeDeployment","direction":"R→M","kind":"route","targets":["post_api_v1_share_deployments_static","post_api_v1_share_deployments_node"],"sourceRef":"附录A:208","support":"partial-ga"},
  {"id":"A-209","legacyIpc":"shareDeployment:get","direction":"R→M","kind":"route","targets":["get_api_v1_share_deployments_deploymentId"],"sourceRef":"附录A:209","support":"partial-ga"},
  {"id":"A-210","legacyIpc":"shareDeployment:getByLocalService","direction":"R→M","kind":"route","targets":["get_api_v1_html_shares_shareId_deployment"],"sourceRef":"附录A:210","support":"partial-ga"},
  {"id":"A-218","legacyIpc":"api:fetch","direction":"R→M","kind":"route","targets":["post_api_v1_model_proxy"],"sourceRef":"附录A:218","support":"ga"},
  {"id":"A-219","legacyIpc":"api:stream","direction":"R→M + M→R","kind":"route","targets":["post_api_v1_model_stream"],"sourceRef":"附录A:219","support":"ga"},
  {"id":"A-220","legacyIpc":"api:stream:cancel","direction":"R→M","kind":"route","targets":["post_api_v1_model_stream_requestId_abort"],"sourceRef":"附录A:220","support":"ga"},
  {"id":"A-221","legacyIpc":"get-api-config","direction":"R→M","kind":"route","targets":["get_api_v1_model_config"],"sourceRef":"附录A:221","support":"ga"},
  {"id":"A-222","legacyIpc":"check-api-config","direction":"R→M","kind":"route","targets":["post_api_v1_model_config_check"],"sourceRef":"附录A:222","support":"ga"},
  {"id":"A-223","legacyIpc":"save-api-config","direction":"R→M","kind":"route","targets":["put_api_v1_model_config"],"sourceRef":"附录A:223","support":"ga"},
  {"id":"A-224","legacyIpc":"generate-session-title","direction":"R→M","kind":"route","targets":["post_api_v1_sessions_id_title_generation","post_api_v1_sessions_id"],"sourceRef":"附录A:224","support":"ga"},
  {"id":"A-232","legacyIpc":"auth:login","direction":"R→M","kind":"route","targets":["post_auth_login","post_oauth_authorize"],"sourceRef":"附录A:232","support":"ga"},
  {"id":"A-233","legacyIpc":"auth:exchange","direction":"R→M","kind":"route","targets":["post_oauth_token","post_auth_callback"],"sourceRef":"附录A:233","support":"ga"},
  {"id":"A-234","legacyIpc":"auth:callback","direction":"M→R","kind":"channel","targets":[],"sourceRef":"附录A:234","support":"ga"},
  {"id":"A-236","legacyIpc":"auth:getUser","direction":"R→M","kind":"route","targets":["get_auth_me"],"sourceRef":"附录A:236","support":"ga"},
  {"id":"A-237","legacyIpc":"auth:getProfileSummary","direction":"R→M","kind":"route","targets":["get_auth_profile_summary"],"sourceRef":"附录A:237","support":"ga"},
  {"id":"A-238","legacyIpc":"auth:getQuota","direction":"R→M","kind":"route","targets":["get_api_v1_billing_account"],"sourceRef":"附录A:238","support":"ga"},
  {"id":"A-239","legacyIpc":"auth:getPricingCatalog","direction":"R→M","kind":"route","targets":["get_api_v1_pricing_models"],"sourceRef":"附录A:239","support":"ga"},
  {"id":"A-240","legacyIpc":"auth:getModels","direction":"R→M","kind":"route","targets":["get_api_v1_models"],"sourceRef":"附录A:240","support":"ga"},
  {"id":"A-241","legacyIpc":"auth:refreshToken","direction":"R→M","kind":"route","targets":["post_auth_refresh"],"sourceRef":"附录A:241","support":"ga"},
  {"id":"A-243","legacyIpc":"auth:logout","direction":"R→M","kind":"route","targets":["post_auth_logout"],"sourceRef":"附录A:243","support":"ga"},
  {"id":"A-251","legacyIpc":"store:get","direction":"R→M","kind":"route","targets":["get_api_v1_kv_key"],"sourceRef":"附录A:251","support":"ga"},
  {"id":"A-252","legacyIpc":"store:set","direction":"R→M","kind":"route","targets":["put_api_v1_kv_key"],"sourceRef":"附录A:252","support":"ga"},
  {"id":"A-253","legacyIpc":"store:remove","direction":"R→M","kind":"route","targets":["delete_api_v1_kv_key"],"sourceRef":"附录A:253","support":"ga"},
  {"id":"A-254","legacyIpc":"enterprise:getConfig","direction":"R→M","kind":"route","targets":["get_api_v1_config_enterprise"],"sourceRef":"附录A:254","support":"ga"},
  {"id":"A-262","legacyIpc":"skills:list","direction":"R→M","kind":"route","targets":["get_api_v1_skills"],"sourceRef":"附录A:262","support":"ga"},
  {"id":"A-263","legacyIpc":"skills:setEnabled","direction":"R→M","kind":"route","targets":["patch_api_v1_skills_id"],"sourceRef":"附录A:263","support":"ga"},
  {"id":"A-264","legacyIpc":"skills:delete","direction":"R→M","kind":"route","targets":["delete_api_v1_skills_id"],"sourceRef":"附录A:264","support":"ga"},
  {"id":"A-265","legacyIpc":"skills:download","direction":"R→M","kind":"route","targets":["post_api_v1_skills_install"],"sourceRef":"附录A:265","support":"ga"},
  {"id":"A-266","legacyIpc":"skills:upgrade","direction":"R→M","kind":"route","targets":["post_api_v1_skills_id_upgrade"],"sourceRef":"附录A:266","support":"ga"},
  {"id":"A-267","legacyIpc":"skills:confirmInstall","direction":"R→M","kind":"route","targets":["post_api_v1_skills_id_confirm"],"sourceRef":"附录A:267","support":"ga"},
  {"id":"A-269","legacyIpc":"skills:autoRoutingPrompt","direction":"R→M","kind":"route","targets":["get_api_v1_skills_routing_prompt"],"sourceRef":"附录A:269","support":"ga"},
  {"id":"A-270","legacyIpc":"skills:getConfig","direction":"R→M","kind":"route","targets":["get_api_v1_skills_id_config"],"sourceRef":"附录A:270","support":"ga"},
  {"id":"A-271","legacyIpc":"skills:setConfig","direction":"R→M","kind":"route","targets":["put_api_v1_skills_id_config"],"sourceRef":"附录A:271","support":"ga"},
  {"id":"A-272","legacyIpc":"skills:testEmailConnectivity","direction":"R→M","kind":"route","targets":["post_api_v1_skills_id_test"],"sourceRef":"附录A:272","support":"ga"},
  {"id":"A-273","legacyIpc":"skills:fetchMarketplace","direction":"R→M","kind":"route","targets":["get_api_v1_skills_marketplace"],"sourceRef":"附录A:273","support":"ga"},
  {"id":"A-274","legacyIpc":"skills:detectFromOpenClaw","direction":"R→M","kind":"route","targets":["post_api_v1_skills_sync"],"sourceRef":"附录A:274","support":"ga"},
  {"id":"A-275","legacyIpc":"skills:syncFromOpenClaw","direction":"R→M","kind":"route","targets":["post_api_v1_skills_sync"],"sourceRef":"附录A:275","support":"ga"},
  {"id":"A-276","legacyIpc":"skills:refreshPluginSkillIds","direction":"R→M","kind":"route","targets":["post_api_v1_skills_sync"],"sourceRef":"附录A:276","support":"ga"},
  {"id":"A-277","legacyIpc":"kits:fetchStore","direction":"R→M","kind":"route","targets":["get_api_v1_kits_marketplace"],"sourceRef":"附录A:277","support":"ga"},
  {"id":"A-278","legacyIpc":"kits:install","direction":"R→M","kind":"route","targets":["post_api_v1_kits_install"],"sourceRef":"附录A:278","support":"ga"},
  {"id":"A-279","legacyIpc":"kits:uninstall","direction":"R→M","kind":"route","targets":["delete_api_v1_kits_id"],"sourceRef":"附录A:279","support":"ga"},
  {"id":"A-280","legacyIpc":"kits:listInstalled","direction":"R→M","kind":"route","targets":["get_api_v1_kits_installed"],"sourceRef":"附录A:280","support":"ga"},
  {"id":"A-288","legacyIpc":"mcp:list","direction":"R→M","kind":"route","targets":["get_api_v1_mcp_servers"],"sourceRef":"附录A:288","support":"ga"},
  {"id":"A-289","legacyIpc":"mcp:create","direction":"R→M","kind":"route","targets":["post_api_v1_mcp_servers"],"sourceRef":"附录A:289","support":"ga"},
  {"id":"A-290","legacyIpc":"mcp:update","direction":"R→M","kind":"route","targets":["patch_api_v1_mcp_servers_id"],"sourceRef":"附录A:290","support":"ga"},
  {"id":"A-291","legacyIpc":"mcp:delete","direction":"R→M","kind":"route","targets":["delete_api_v1_mcp_servers_id"],"sourceRef":"附录A:291","support":"ga"},
  {"id":"A-292","legacyIpc":"mcp:setEnabled","direction":"R→M","kind":"route","targets":["patch_api_v1_mcp_servers_id"],"sourceRef":"附录A:292","support":"ga"},
  {"id":"A-293","legacyIpc":"mcp:retryLaunchResolution","direction":"R→M","kind":"route","targets":["post_api_v1_mcp_servers_id_launch_resolution_retry"],"sourceRef":"附录A:293","support":"ga"},
  {"id":"A-294","legacyIpc":"mcp:fetchMarketplace","direction":"R→M","kind":"route","targets":["get_api_v1_mcp_marketplace"],"sourceRef":"附录A:294","support":"ga"},
  {"id":"A-302","legacyIpc":"plugins:list","direction":"R→M","kind":"route","targets":["get_api_v1_plugins"],"sourceRef":"附录A:302","support":"ga"},
  {"id":"A-303","legacyIpc":"plugins:detect","direction":"R→M","kind":"route","targets":["post_api_v1_plugins_detect"],"sourceRef":"附录A:303","support":"ga"},
  {"id":"A-304","legacyIpc":"plugins:sync","direction":"R→M","kind":"route","targets":["post_api_v1_plugins_sync"],"sourceRef":"附录A:304","support":"ga"},
  {"id":"A-305","legacyIpc":"plugins:install","direction":"R→M","kind":"route","targets":["post_api_v1_plugins_install"],"sourceRef":"附录A:305","support":"ga"},
  {"id":"A-306","legacyIpc":"plugins:uninstall","direction":"R→M","kind":"route","targets":["delete_api_v1_plugins_id"],"sourceRef":"附录A:306","support":"ga"},
  {"id":"A-307","legacyIpc":"plugins:set-enabled","direction":"R→M","kind":"route","targets":["patch_api_v1_plugins_id"],"sourceRef":"附录A:307","support":"ga"},
  {"id":"A-308","legacyIpc":"plugins:get-config-schema","direction":"R→M","kind":"route","targets":["get_api_v1_plugins_id_config_schema"],"sourceRef":"附录A:308","support":"ga"},
  {"id":"A-309","legacyIpc":"plugins:save-config","direction":"R→M","kind":"route","targets":["put_api_v1_plugins_id_config"],"sourceRef":"附录A:309","support":"ga"},
  {"id":"A-310","legacyIpc":"plugins:batch-save","direction":"R→M","kind":"route","targets":["post_api_v1_plugins_batch_save"],"sourceRef":"附录A:310","support":"ga"},
  {"id":"A-311","legacyIpc":"plugins:check-updates","direction":"R→M","kind":"route","targets":["get_api_v1_plugins_updates_check"],"sourceRef":"附录A:311","support":"ga"},
  {"id":"A-312","legacyIpc":"plugins:update","direction":"R→M","kind":"route","targets":["post_api_v1_plugins_id_update"],"sourceRef":"附录A:312","support":"ga"},
  {"id":"A-322","legacyIpc":"scheduledTask:list","direction":"R→M","kind":"route","targets":["get_api_v1_scheduled_tasks"],"sourceRef":"附录A:322","support":"ga"},
  {"id":"A-323","legacyIpc":"scheduledTask:get","direction":"R→M","kind":"route","targets":["get_api_v1_scheduled_tasks_id"],"sourceRef":"附录A:323","support":"ga"},
  {"id":"A-324","legacyIpc":"scheduledTask:create","direction":"R→M","kind":"route","targets":["post_api_v1_scheduled_tasks"],"sourceRef":"附录A:324","support":"ga"},
  {"id":"A-325","legacyIpc":"scheduledTask:update","direction":"R→M","kind":"route","targets":["patch_api_v1_scheduled_tasks_id"],"sourceRef":"附录A:325","support":"ga"},
  {"id":"A-326","legacyIpc":"scheduledTask:delete","direction":"R→M","kind":"route","targets":["delete_api_v1_scheduled_tasks_id"],"sourceRef":"附录A:326","support":"ga"},
  {"id":"A-327","legacyIpc":"scheduledTask:toggle","direction":"R→M","kind":"route","targets":["patch_api_v1_scheduled_tasks_id"],"sourceRef":"附录A:327","support":"ga"},
  {"id":"A-328","legacyIpc":"scheduledTask:runManually","direction":"R→M","kind":"route","targets":["post_api_v1_scheduled_tasks_id_runs"],"sourceRef":"附录A:328","support":"ga"},
  {"id":"A-329","legacyIpc":"scheduledTask:stop","direction":"R→M","kind":"route","targets":["post_api_v1_scheduled_tasks_id_stop"],"sourceRef":"附录A:329","support":"ga"},
  {"id":"A-330","legacyIpc":"scheduledTask:listRuns","direction":"R→M","kind":"route","targets":["get_api_v1_scheduled_tasks_id_runs"],"sourceRef":"附录A:330","support":"ga"},
  {"id":"A-331","legacyIpc":"scheduledTask:countRuns","direction":"R→M","kind":"route","targets":["get_api_v1_scheduled_tasks_id_runs_count"],"sourceRef":"附录A:331","support":"ga"},
  {"id":"A-332","legacyIpc":"scheduledTask:listAllRuns","direction":"R→M","kind":"route","targets":["get_api_v1_scheduled_tasks_runs"],"sourceRef":"附录A:332","support":"ga"},
  {"id":"A-333","legacyIpc":"scheduledTask:resolveSession","direction":"R→M","kind":"route","targets":["get_api_v1_scheduled_tasks_runs_runId_session"],"sourceRef":"附录A:333","support":"ga"},
  {"id":"A-334","legacyIpc":"scheduledTask:listChannels","direction":"R→M","kind":"route","targets":["get_api_v1_scheduled_tasks_channels"],"sourceRef":"附录A:334","support":"ga"},
  {"id":"A-335","legacyIpc":"scheduledTask:listChannelConversations","direction":"R→M","kind":"route","targets":["get_api_v1_scheduled_tasks_channels_ch_conversations"],"sourceRef":"附录A:335","support":"partial-ga"},
  {"id":"A-343","legacyIpc":"openclaw:engine:getStatus","direction":"R→M","kind":"route","targets":["get_api_v1_runtime_status"],"sourceRef":"附录A:343","support":"ga"},
  {"id":"A-344","legacyIpc":"openclaw:engine:install","direction":"R→M","kind":"route","targets":["post_api_v1_runtime_provision"],"sourceRef":"附录A:344","support":"ga"},
  {"id":"A-345","legacyIpc":"openclaw:engine:retryInstall","direction":"R→M","kind":"route","targets":["post_api_v1_runtime_provision"],"sourceRef":"附录A:345","support":"ga"},
  {"id":"A-346","legacyIpc":"openclaw:engine:restartGateway","direction":"R→M","kind":"route","targets":["post_api_v1_runtime_restart"],"sourceRef":"附录A:346","support":"ga"},
  {"id":"A-347","legacyIpc":"openclaw:engine:repairGatewayState","direction":"R→M","kind":"route","targets":["post_api_v1_runtime_repair"],"sourceRef":"附录A:347","support":"ga"},
  {"id":"A-348","legacyIpc":"openclaw:session:patch","direction":"R→M","kind":"route","targets":["patch_api_v1_sessions_id_runtime"],"sourceRef":"附录A:348","support":"ga"},
  {"id":"A-349","legacyIpc":"openclaw:dataMigration:backup","direction":"R→M","kind":"route","targets":["post_api_v1_runtime_migration_backups"],"sourceRef":"附录A:349","support":"ga"},
  {"id":"A-350","legacyIpc":"openclaw:dataMigration:restore","direction":"R→M","kind":"route","targets":["post_api_v1_runtime_migration_restores"],"sourceRef":"附录A:350","support":"ga"},
  {"id":"A-351","legacyIpc":"openclaw:dataMigration:getLastRestoreResult","direction":"R→M","kind":"route","targets":["get_api_v1_runtime_migration_last_restore"],"sourceRef":"附录A:351","support":"ga"},
  {"id":"A-352","legacyIpc":"openclaw:sessionPolicy:get","direction":"R→M","kind":"route","targets":["get_api_v1_runtime_session_policy"],"sourceRef":"附录A:352","support":"ga"},
  {"id":"A-353","legacyIpc":"openclaw:sessionPolicy:set","direction":"R→M","kind":"route","targets":["put_api_v1_runtime_session_policy"],"sourceRef":"附录A:353","support":"ga"},
  {"id":"A-365","legacyIpc":"asr:realtime:createSession","direction":"R→M","kind":"route","targets":["post_api_v1_asr_sessions","post_api_v1_asr_sessions_asrSessionId_stream","post_api_v1_model_stream"],"sourceRef":"附录A:365","support":"ga"},
  {"id":"A-373","legacyIpc":"dialog:selectDirectory","direction":"R→M","kind":"route","targets":["get_api_v1_workspaces_wid_files_tree"],"sourceRef":"附录A:373","support":"ga"},
  {"id":"A-374","legacyIpc":"dialog:selectFile / dialog:selectFiles","direction":"R→M","kind":"route","targets":["post_api_v1_workspaces_wid_files_upload"],"sourceRef":"附录A:374","support":"ga"},
  {"id":"A-375","legacyIpc":"dialog:saveInlineFile","direction":"R→M","kind":"route","targets":["post_api_v1_workspaces_wid_files_upload"],"sourceRef":"附录A:375","support":"ga"},
  {"id":"A-376","legacyIpc":"dialog:readFileAsDataUrl","direction":"R→M","kind":"route","targets":["get_api_v1_workspaces_wid_files_download"],"sourceRef":"附录A:376","support":"ga"},
  {"id":"A-377","legacyIpc":"dialog:statFile","direction":"R→M","kind":"route","targets":["get_api_v1_workspaces_wid_files_stat"],"sourceRef":"附录A:377","support":"ga"},
  {"id":"A-378","legacyIpc":"dialog:readTextFile","direction":"R→M","kind":"route","targets":["get_api_v1_workspaces_wid_files_download"],"sourceRef":"附录A:378","support":"ga"},
  {"id":"A-379","legacyIpc":"dialog:generateThumbnail","direction":"R→M","kind":"route","targets":["get_api_v1_workspaces_wid_files_thumbnail"],"sourceRef":"附录A:379","support":"ga"},
  {"id":"A-446","legacyIpc":"cowork:stream:message","direction":"M→R","kind":"channel","targets":["message"],"sourceRef":"附录A:446","support":"ga"},
  {"id":"A-447","legacyIpc":"cowork:stream:messageUpdate","direction":"M→R","kind":"channel","targets":["messageUpdate"],"sourceRef":"附录A:447","support":"ga"},
  {"id":"A-448","legacyIpc":"cowork:stream:sessionStatus","direction":"M→R","kind":"channel","targets":["sessionStatus"],"sourceRef":"附录A:448","support":"ga"},
  {"id":"A-449","legacyIpc":"cowork:stream:contextUsage","direction":"M→R","kind":"channel","targets":["contextUsage"],"sourceRef":"附录A:449","support":"ga"},
  {"id":"A-450","legacyIpc":"cowork:stream:contextMaintenance","direction":"M→R","kind":"channel","targets":["contextMaintenance"],"sourceRef":"附录A:450","support":"ga"},
  {"id":"A-451","legacyIpc":"cowork:stream:goal (CoworkIpcChannel.StreamGoal)","direction":"M→R","kind":"channel","targets":["goal"],"sourceRef":"附录A:451","support":"ga"},
  {"id":"A-452","legacyIpc":"cowork:stream:permission","direction":"M→R","kind":"channel","targets":["permission"],"sourceRef":"附录A:452","support":"ga"},
  {"id":"A-453","legacyIpc":"cowork:stream:permissionDismiss","direction":"M→R","kind":"channel","targets":["permissionDismiss"],"sourceRef":"附录A:453","support":"ga"},
  {"id":"A-454","legacyIpc":"cowork:stream:complete","direction":"M→R","kind":"channel","targets":["complete"],"sourceRef":"附录A:454","support":"ga"},
  {"id":"A-455","legacyIpc":"cowork:stream:error","direction":"M→R","kind":"channel","targets":["error"],"sourceRef":"附录A:455","support":"ga"},
  {"id":"A-465","legacyIpc":"api:stream:${id}:data","direction":"M→R","kind":"channel","targets":["apiStreamChunk"],"sourceRef":"附录A:465","support":"ga"},
  {"id":"A-466","legacyIpc":"api:stream:${id}:done","direction":"M→R","kind":"channel","targets":["apiStreamDone"],"sourceRef":"附录A:466","support":"ga"},
  {"id":"A-467","legacyIpc":"api:stream:${id}:error","direction":"M→R","kind":"channel","targets":["apiStreamError"],"sourceRef":"附录A:467","support":"ga"},
  {"id":"A-468","legacyIpc":"api:stream:${id}:abort","direction":"M→R","kind":"channel","targets":["apiStreamAbort"],"sourceRef":"附录A:468","support":"ga"},
  {"id":"A-474","legacyIpc":"cowork:sessions:changed","direction":"M→R","kind":"channel","targets":["sessionsChanged"],"sourceRef":"附录A:474","support":"ga"},
  {"id":"A-475","legacyIpc":"cowork:media:statusPollUpdate (MediaStatusPollUpdate)","direction":"M→R","kind":"channel","targets":["mediaStatusPollUpdate"],"sourceRef":"附录A:475","support":"ga"},
  {"id":"A-476","legacyIpc":"cowork:session:openFromNotification (OpenSessionFromNotification)","direction":"M→R","kind":"channel","targets":["openSessionFromNotification"],"sourceRef":"附录A:476","support":"ga"},
  {"id":"A-477","legacyIpc":"files:changed（桥兼容别名 artifact:file:changed）","direction":"M→R","kind":"channel","targets":["filesChanged"],"sourceRef":"附录A:477","support":"ga"},
  {"id":"A-478","legacyIpc":"skills:changed","direction":"M→R","kind":"channel","targets":["skillsChanged"],"sourceRef":"附录A:478","support":"ga"},
  {"id":"A-479","legacyIpc":"mcp:changed","direction":"M→R","kind":"channel","targets":["mcpChanged"],"sourceRef":"附录A:479","support":"ga"},
  {"id":"A-480","legacyIpc":"auth:quotaChanged","direction":"M→R","kind":"channel","targets":["quotaChanged"],"sourceRef":"附录A:480","support":"ga"},
  {"id":"A-481","legacyIpc":"plugins:install-log","direction":"M→R","kind":"channel","targets":["pluginsInstallLog"],"sourceRef":"附录A:481","support":"ga"},
  {"id":"A-482","legacyIpc":"openclaw:engine:onProgress (OpenClawEngineIpc.OnProgress)","direction":"M→R","kind":"channel","targets":["openclawEngineProgress"],"sourceRef":"附录A:482","support":"ga"},
  {"id":"A-483","legacyIpc":"scheduledTask:statusUpdate","direction":"M→R","kind":"channel","targets":["taskStatus"],"sourceRef":"附录A:483","support":"ga"},
  {"id":"A-484","legacyIpc":"scheduledTask:runUpdate","direction":"M→R","kind":"channel","targets":["taskRun"],"sourceRef":"附录A:484","support":"ga"},
  {"id":"A-485","legacyIpc":"scheduledTask:refresh","direction":"M→R","kind":"channel","targets":["taskRefresh"],"sourceRef":"附录A:485","support":"ga"},
  {"id":"A-514","legacyIpc":"app:getVersion / getSystemLocale / getKeyfromAttribution","direction":"应用信息","kind":"channel","targets":[],"sourceRef":"附录A:514","support":"ga"},
] as const satisfies readonly IpcGaInventoryEntry[];

