import type { ZodType } from 'zod';
import * as Schemas from '../index.schemas.js';

export const HttpMethod = { Get: 'GET', Post: 'POST', Put: 'PUT', Patch: 'PATCH', Delete: 'DELETE' } as const;
export type HttpMethod = (typeof HttpMethod)[keyof typeof HttpMethod];
export const RouteSupport = { Ga: 'ga', Unsupported: 'unsupported' } as const;

export interface RouteRegistryEntry {
  readonly operationId: string; readonly method: HttpMethod; readonly path: string; readonly domain: string;
  readonly requestName: string; readonly request: ZodType; readonly responseName: string; readonly response: ZodType;
  readonly errors: readonly string[]; readonly auth: 'public' | 'access-token'; readonly legacyBridgePaths: readonly string[];
  readonly sourceRefs: readonly string[]; readonly support: 'ga' | 'unsupported';
}

const route = (method: HttpMethod, path: string, operationId: string, requestName: keyof typeof Schemas, responseName: keyof typeof Schemas): RouteRegistryEntry => ({
  operationId, method, path, domain: path.split('/').filter(Boolean)[2] ?? 'auth', requestName, request: Schemas[requestName], responseName, response: Schemas[responseName],
  errors: ['VALIDATION_FAILED', 'UNAUTHENTICATED', 'NOT_FOUND', 'INTERNAL_ERROR'], auth: path.startsWith('/auth/') || path.startsWith('/oauth/') ? 'public' : 'access-token',
  legacyBridgePaths: [], sourceRefs: ['附录A', '19§3.3'], support: method === 'POST' && path === '/api/v1/share-deployments/node' ? 'unsupported' : 'ga',
});

export const RouteRegistry = [
  route('GET', '/api/v1/agents', 'get_api_v1_agents', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/agents', 'post_api_v1_agents', 'GenericRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/agents/{id}', 'delete_api_v1_agents_id', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/agents/{id}', 'get_api_v1_agents_id', 'EmptyRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/agents/{id}', 'patch_api_v1_agents_id', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/agents/preset-templates', 'get_api_v1_agents_preset_templates', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/agents/presets', 'get_api_v1_agents_presets', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/agents/presets/{presetId}/install', 'post_api_v1_agents_presets_presetId_install', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/artifacts/{artifactId}/preview', 'post_api_v1_artifacts_artifactId_preview', 'GenericRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/artifacts/preview-sessions/{previewSessionId}', 'delete_api_v1_artifacts_preview_sessions_previewSessionId', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/asr/sessions', 'post_api_v1_asr_sessions', 'AsrSessionCreateRequest', 'AsrSessionCreateResponse'),
  route('POST', '/api/v1/asr/sessions/{asrSessionId}/stream', 'post_api_v1_asr_sessions_asrSessionId_stream', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/billing/account', 'get_api_v1_billing_account', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/billing/byok', 'post_api_v1_billing_byok', 'GenericRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/billing/byok/{provider}', 'delete_api_v1_billing_byok_provider', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/billing/plan', 'get_api_v1_billing_plan', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/billing/usage', 'get_api_v1_billing_usage', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/config/app-info', 'get_api_v1_config_app_info', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/config/enterprise', 'get_api_v1_config_enterprise', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/cowork/bootstrap', 'get_api_v1_cowork_bootstrap', 'EmptyRequest', 'GenericResponse'),
  route('PUT', '/api/v1/cowork/bootstrap', 'put_api_v1_cowork_bootstrap', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/cowork/config', 'get_api_v1_cowork_config', 'EmptyRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/cowork/config', 'patch_api_v1_cowork_config', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/cowork/dreaming/diary', 'get_api_v1_cowork_dreaming_diary', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/cowork/dreaming/status', 'get_api_v1_cowork_dreaming_status', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/cowork/memory/entries', 'get_api_v1_cowork_memory_entries', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/cowork/memory/entries', 'post_api_v1_cowork_memory_entries', 'GenericRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/cowork/memory/entries/{id}', 'delete_api_v1_cowork_memory_entries_id', 'EmptyRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/cowork/memory/entries/{id}', 'patch_api_v1_cowork_memory_entries_id', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/cowork/memory/stats', 'get_api_v1_cowork_memory_stats', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/html-shares', 'get_api_v1_html_shares', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/html-shares', 'post_api_v1_html_shares', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/html-shares/{id}', 'get_api_v1_html_shares_id', 'EmptyRequest', 'GenericResponse'),
  route('PUT', '/api/v1/html-shares/{id}', 'put_api_v1_html_shares_id', 'GenericRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/html-shares/{id}/access-mode', 'patch_api_v1_html_shares_id_access_mode', 'GenericRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/html-shares/{id}/status', 'patch_api_v1_html_shares_id_status', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/html-shares/{shareId}/deployment', 'get_api_v1_html_shares_shareId_deployment', 'EmptyRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/kits/{id}', 'delete_api_v1_kits_id', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/kits/install', 'post_api_v1_kits_install', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/kits/installed', 'get_api_v1_kits_installed', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/kits/marketplace', 'get_api_v1_kits_marketplace', 'EmptyRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/kv/{key}', 'delete_api_v1_kv_key', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/kv/{key}', 'get_api_v1_kv_key', 'EmptyRequest', 'GenericResponse'),
  route('PUT', '/api/v1/kv/{key}', 'put_api_v1_kv_key', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/mcp/marketplace', 'get_api_v1_mcp_marketplace', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/mcp/servers', 'get_api_v1_mcp_servers', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/mcp/servers', 'post_api_v1_mcp_servers', 'GenericRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/mcp/servers/{id}', 'delete_api_v1_mcp_servers_id', 'EmptyRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/mcp/servers/{id}', 'patch_api_v1_mcp_servers_id', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/mcp/servers/{id}/launch-resolution/retry', 'post_api_v1_mcp_servers_id_launch_resolution_retry', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/media/models', 'get_api_v1_media_models', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/media/tasks/{taskId}', 'get_api_v1_media_tasks_taskId', 'EmptyRequest', 'MediaTaskStatusResponse'),
  route('POST', '/api/v1/media/tasks/{taskId}/cancel', 'post_api_v1_media_tasks_taskId_cancel', 'EmptyRequest', 'MediaCancelResponse'),
  route('GET', '/api/v1/model/config', 'get_api_v1_model_config', 'EmptyRequest', 'GenericResponse'),
  route('PUT', '/api/v1/model/config', 'put_api_v1_model_config', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/model/config/check', 'post_api_v1_model_config_check', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/model/proxy', 'post_api_v1_model_proxy', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/model/stream', 'post_api_v1_model_stream', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/model/stream/{requestId}/abort', 'post_api_v1_model_stream_requestId_abort', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/models', 'get_api_v1_models', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/models/{id}', 'get_api_v1_models_id', 'EmptyRequest', 'ModelDetailResponse'),
  route('GET', '/api/v1/plugins', 'get_api_v1_plugins', 'EmptyRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/plugins/{id}', 'delete_api_v1_plugins_id', 'EmptyRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/plugins/{id}', 'patch_api_v1_plugins_id', 'GenericRequest', 'GenericResponse'),
  route('PUT', '/api/v1/plugins/{id}/config', 'put_api_v1_plugins_id_config', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/plugins/{id}/config-schema', 'get_api_v1_plugins_id_config_schema', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/plugins/{id}/update', 'post_api_v1_plugins_id_update', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/plugins/batch-save', 'post_api_v1_plugins_batch_save', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/plugins/detect', 'post_api_v1_plugins_detect', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/plugins/install', 'post_api_v1_plugins_install', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/plugins/sync', 'post_api_v1_plugins_sync', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/plugins/updates/check', 'get_api_v1_plugins_updates_check', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/pricing/models', 'get_api_v1_pricing_models', 'EmptyRequest', 'PricingCatalogResponse'),
  route('POST', '/api/v1/privacy/deletions', 'post_api_v1_privacy_deletions', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/privacy/deletions/{deletionId}', 'get_api_v1_privacy_deletions_deletionId', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/privacy/exports', 'post_api_v1_privacy_exports', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/privacy/exports/{exportId}', 'get_api_v1_privacy_exports_exportId', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/runtime/migration/backups', 'post_api_v1_runtime_migration_backups', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/runtime/migration/last-restore', 'get_api_v1_runtime_migration_last_restore', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/runtime/migration/restores', 'post_api_v1_runtime_migration_restores', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/runtime/provision', 'post_api_v1_runtime_provision', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/runtime/repair', 'post_api_v1_runtime_repair', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/runtime/restart', 'post_api_v1_runtime_restart', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/runtime/session-policy', 'get_api_v1_runtime_session_policy', 'EmptyRequest', 'GenericResponse'),
  route('PUT', '/api/v1/runtime/session-policy', 'put_api_v1_runtime_session_policy', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/runtime/status', 'get_api_v1_runtime_status', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/scheduled-tasks', 'get_api_v1_scheduled_tasks', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/scheduled-tasks', 'post_api_v1_scheduled_tasks', 'GenericRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/scheduled-tasks/{id}', 'delete_api_v1_scheduled_tasks_id', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/scheduled-tasks/{id}', 'get_api_v1_scheduled_tasks_id', 'EmptyRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/scheduled-tasks/{id}', 'patch_api_v1_scheduled_tasks_id', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/scheduled-tasks/{id}/runs', 'get_api_v1_scheduled_tasks_id_runs', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/scheduled-tasks/{id}/runs', 'post_api_v1_scheduled_tasks_id_runs', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/scheduled-tasks/{id}/runs/count', 'get_api_v1_scheduled_tasks_id_runs_count', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/scheduled-tasks/{id}/stop', 'post_api_v1_scheduled_tasks_id_stop', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/scheduled-tasks/channels', 'get_api_v1_scheduled_tasks_channels', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/scheduled-tasks/channels/{ch}/conversations', 'get_api_v1_scheduled_tasks_channels_ch_conversations', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/scheduled-tasks/runs', 'get_api_v1_scheduled_tasks_runs', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/scheduled-tasks/runs/{runId}/session', 'get_api_v1_scheduled_tasks_runs_runId_session', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/sessions', 'get_api_v1_sessions', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions', 'post_api_v1_sessions', 'StartSessionRequest', 'StartSessionResponse'),
  route('DELETE', '/api/v1/sessions/{id}', 'delete_api_v1_sessions_id', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/sessions/{id}', 'get_api_v1_sessions_id', 'EmptyRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/sessions/{id}', 'patch_api_v1_sessions_id', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}', 'post_api_v1_sessions_id', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/compact-context', 'post_api_v1_sessions_id_compact_context', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/sessions/{id}/context-usage', 'get_api_v1_sessions_id_context_usage', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/exports/result-image', 'post_api_v1_sessions_id_exports_result_image', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/exports/text', 'post_api_v1_sessions_id_exports_text', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/fork', 'post_api_v1_sessions_id_fork', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/sessions/{id}/managed', 'get_api_v1_sessions_id_managed', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/sessions/{id}/messages', 'get_api_v1_sessions_id_messages', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/permissions/{requestId}/respond', 'post_api_v1_sessions_id_permissions_requestId_respond', 'PermissionRespondRequest', 'GenericResponse'),
  route('GET', '/api/v1/sessions/{id}/rail-index', 'get_api_v1_sessions_id_rail_index', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/result-image/chunks', 'post_api_v1_sessions_id_result_image_chunks', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/result-image/files', 'post_api_v1_sessions_id_result_image_files', 'GenericRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/sessions/{id}/runtime', 'patch_api_v1_sessions_id_runtime', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/stop', 'post_api_v1_sessions_id_stop', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/sessions/{id}/subagents', 'get_api_v1_sessions_id_subagents', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/title-generation', 'post_api_v1_sessions_id_title_generation', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/{id}/turns', 'post_api_v1_sessions_id_turns', 'ContinueTurnRequest', 'TurnAcceptedResponse'),
  route('POST', '/api/v1/sessions/{id}/viewed', 'post_api_v1_sessions_id_viewed', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/sessions/batch-delete', 'post_api_v1_sessions_batch_delete', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/share-deployments/{deploymentId}', 'get_api_v1_share_deployments_deploymentId', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/share-deployments/analyze', 'post_api_v1_share_deployments_analyze', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/share-deployments/candidates', 'post_api_v1_share_deployments_candidates', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/share-deployments/node', 'post_api_v1_share_deployments_node', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/share-deployments/static', 'post_api_v1_share_deployments_static', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/skills', 'get_api_v1_skills', 'EmptyRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/skills/{id}', 'delete_api_v1_skills_id', 'EmptyRequest', 'GenericResponse'),
  route('PATCH', '/api/v1/skills/{id}', 'patch_api_v1_skills_id', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/skills/{id}/config', 'get_api_v1_skills_id_config', 'EmptyRequest', 'GenericResponse'),
  route('PUT', '/api/v1/skills/{id}/config', 'put_api_v1_skills_id_config', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/skills/{id}/confirm', 'post_api_v1_skills_id_confirm', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/skills/{id}/test', 'post_api_v1_skills_id_test', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/skills/{id}/upgrade', 'post_api_v1_skills_id_upgrade', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/skills/install', 'post_api_v1_skills_install', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/skills/marketplace', 'get_api_v1_skills_marketplace', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/skills/routing-prompt', 'get_api_v1_skills_routing_prompt', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/skills/sync', 'post_api_v1_skills_sync', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/stream/ticket', 'post_api_v1_stream_ticket', 'StreamTicketRequest', 'StreamTicketResponse'),
  route('DELETE', '/api/v1/subagents/{runId}', 'delete_api_v1_subagents_runId', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/subagents/{runId}/messages', 'get_api_v1_subagents_runId_messages', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/workspaces', 'get_api_v1_workspaces', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/workspaces', 'post_api_v1_workspaces', 'GenericRequest', 'GenericResponse'),
  route('DELETE', '/api/v1/workspaces/{wid}/files', 'delete_api_v1_workspaces_wid_files', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/workspaces/{wid}/files/download', 'get_api_v1_workspaces_wid_files_download', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/workspaces/{wid}/files/stat', 'get_api_v1_workspaces_wid_files_stat', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/workspaces/{wid}/files/thumbnail', 'get_api_v1_workspaces_wid_files_thumbnail', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/api/v1/workspaces/{wid}/files/tree', 'get_api_v1_workspaces_wid_files_tree', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/api/v1/workspaces/{wid}/files/upload', 'post_api_v1_workspaces_wid_files_upload', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/workspaces/{wid}/uploads', 'post_api_v1_workspaces_wid_uploads', 'GenericRequest', 'GenericResponse'),
  route('POST', '/api/v1/workspaces/{wid}/uploads/{id}/complete', 'post_api_v1_workspaces_wid_uploads_id_complete', 'GenericRequest', 'GenericResponse'),
  route('GET', '/api/v1/workspaces/recent', 'get_api_v1_workspaces_recent', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/auth/callback', 'post_auth_callback', 'GenericRequest', 'GenericResponse'),
  route('POST', '/auth/login', 'post_auth_login', 'LoginRequest', 'LoginResponse'),
  route('POST', '/auth/logout', 'post_auth_logout', 'EmptyRequest', 'LogoutResponse'),
  route('GET', '/auth/me', 'get_auth_me', 'EmptyRequest', 'GenericResponse'),
  route('GET', '/auth/profile-summary', 'get_auth_profile_summary', 'EmptyRequest', 'GenericResponse'),
  route('POST', '/auth/refresh', 'post_auth_refresh', 'RefreshRequest', 'TokenResponse'),
  route('POST', '/oauth/authorize', 'post_oauth_authorize', 'GenericRequest', 'GenericResponse'),
  route('POST', '/oauth/token', 'post_oauth_token', 'OAuthTokenRequest', 'TokenResponse'),
] as const satisfies readonly RouteRegistryEntry[];

