import type { ErrorCode } from '../errors.js';

export interface RoutePolicyExpectation {
  readonly auth: 'public' | 'access-token' | 'refresh-cookie';
  readonly successStatus: number;
  readonly errors: readonly ErrorCode[];
}

// This independent operation list is intentionally not imported from RouteRegistry. A route
// addition, removal, or rename must update the reviewed policy denominator explicitly.
export const ExpectedRouteOperationIds = [
  'get_api_v1_agents',
  'post_api_v1_agents',
  'delete_api_v1_agents_id',
  'get_api_v1_agents_id',
  'patch_api_v1_agents_id',
  'get_api_v1_agents_preset_templates',
  'get_api_v1_agents_presets',
  'post_api_v1_agents_presets_presetId_install',
  'post_api_v1_artifacts_artifactId_preview',
  'delete_api_v1_artifacts_preview_sessions_previewSessionId',
  'post_api_v1_asr_sessions',
  'get_api_v1_billing_account',
  'post_api_v1_billing_byok',
  'delete_api_v1_billing_byok_provider',
  'get_api_v1_billing_plan',
  'get_api_v1_billing_usage',
  'get_api_v1_config_app_info',
  'get_api_v1_config_enterprise',
  'get_api_v1_cowork_bootstrap',
  'put_api_v1_cowork_bootstrap',
  'get_api_v1_cowork_config',
  'patch_api_v1_cowork_config',
  'get_api_v1_cowork_dreaming_diary',
  'get_api_v1_cowork_dreaming_status',
  'get_api_v1_cowork_memory_entries',
  'post_api_v1_cowork_memory_entries',
  'delete_api_v1_cowork_memory_entries_id',
  'patch_api_v1_cowork_memory_entries_id',
  'get_api_v1_cowork_memory_stats',
  'get_api_v1_html_shares',
  'post_api_v1_html_shares',
  'get_api_v1_html_shares_id',
  'put_api_v1_html_shares_id',
  'patch_api_v1_html_shares_id_access_mode',
  'patch_api_v1_html_shares_id_status',
  'get_api_v1_html_shares_shareId_deployment',
  'delete_api_v1_kits_id',
  'post_api_v1_kits_install',
  'get_api_v1_kits_installed',
  'get_api_v1_kits_marketplace',
  'delete_api_v1_kv_key',
  'get_api_v1_kv_key',
  'put_api_v1_kv_key',
  'get_api_v1_mcp_marketplace',
  'get_api_v1_mcp_servers',
  'post_api_v1_mcp_servers',
  'delete_api_v1_mcp_servers_id',
  'patch_api_v1_mcp_servers_id',
  'post_api_v1_mcp_servers_id_launch_resolution_retry',
  'get_api_v1_media_tasks_taskId',
  'post_api_v1_media_tasks_taskId_cancel',
  'get_api_v1_model_config',
  'put_api_v1_model_config',
  'post_api_v1_model_config_check',
  'post_api_v1_model_proxy',
  'post_api_v1_model_stream',
  'post_api_v1_model_stream_requestId_abort',
  'get_api_v1_models',
  'get_api_v1_models_id',
  'get_api_v1_plugins',
  'delete_api_v1_plugins_id',
  'patch_api_v1_plugins_id',
  'put_api_v1_plugins_id_config',
  'get_api_v1_plugins_id_config_schema',
  'post_api_v1_plugins_id_update',
  'post_api_v1_plugins_batch_save',
  'post_api_v1_plugins_detect',
  'post_api_v1_plugins_install',
  'post_api_v1_plugins_sync',
  'get_api_v1_plugins_updates_check',
  'get_api_v1_pricing_models',
  'post_api_v1_privacy_deletions',
  'get_api_v1_privacy_deletions_deletionId',
  'post_api_v1_privacy_exports',
  'get_api_v1_privacy_exports_exportId',
  'post_api_v1_runtime_migration_backups',
  'get_api_v1_runtime_migration_last_restore',
  'post_api_v1_runtime_migration_restores',
  'post_api_v1_runtime_provision',
  'post_api_v1_runtime_repair',
  'post_api_v1_runtime_restart',
  'get_api_v1_runtime_session_policy',
  'put_api_v1_runtime_session_policy',
  'get_api_v1_runtime_status',
  'get_api_v1_scheduled_tasks',
  'post_api_v1_scheduled_tasks',
  'delete_api_v1_scheduled_tasks_id',
  'get_api_v1_scheduled_tasks_id',
  'patch_api_v1_scheduled_tasks_id',
  'get_api_v1_scheduled_tasks_id_runs',
  'post_api_v1_scheduled_tasks_id_runs',
  'get_api_v1_scheduled_tasks_id_runs_count',
  'post_api_v1_scheduled_tasks_id_stop',
  'get_api_v1_scheduled_tasks_channels',
  'get_api_v1_scheduled_tasks_channels_ch_conversations',
  'get_api_v1_scheduled_tasks_runs',
  'get_api_v1_scheduled_tasks_runs_runId_session',
  'get_api_v1_sessions',
  'post_api_v1_sessions',
  'delete_api_v1_sessions_id',
  'get_api_v1_sessions_id',
  'patch_api_v1_sessions_id',
  'post_api_v1_sessions_id_compact_context',
  'get_api_v1_sessions_id_context_usage',
  'post_api_v1_sessions_id_exports_result_image',
  'post_api_v1_sessions_id_exports_text',
  'post_api_v1_sessions_id_fork',
  'get_api_v1_sessions_id_managed',
  'get_api_v1_sessions_id_messages',
  'post_api_v1_sessions_id_permissions_requestId_respond',
  'get_api_v1_sessions_id_rail_index',
  'post_api_v1_sessions_id_result_image_chunks',
  'post_api_v1_sessions_id_result_image_files',
  'patch_api_v1_sessions_id_runtime',
  'post_api_v1_sessions_id_stop',
  'get_api_v1_sessions_id_subagents',
  'post_api_v1_sessions_id_title_generation',
  'post_api_v1_sessions_id_turns',
  'post_api_v1_sessions_id_viewed',
  'post_api_v1_sessions_batch_delete',
  'get_api_v1_share_deployments_deploymentId',
  'post_api_v1_share_deployments_analyze',
  'post_api_v1_share_deployments_candidates',
  'post_api_v1_share_deployments_node',
  'post_api_v1_share_deployments_static',
  'get_api_v1_skills',
  'delete_api_v1_skills_id',
  'patch_api_v1_skills_id',
  'get_api_v1_skills_id_config',
  'put_api_v1_skills_id_config',
  'post_api_v1_skills_id_confirm',
  'post_api_v1_skills_id_test',
  'post_api_v1_skills_id_upgrade',
  'post_api_v1_skills_install',
  'get_api_v1_skills_marketplace',
  'get_api_v1_skills_routing_prompt',
  'post_api_v1_skills_sync',
  'post_api_v1_stream_ticket',
  'delete_api_v1_subagents_runId',
  'get_api_v1_subagents_runId_messages',
  'get_api_v1_workspaces',
  'post_api_v1_workspaces',
  'delete_api_v1_workspaces_wid_files',
  'get_api_v1_workspaces_wid_files_download',
  'get_api_v1_workspaces_wid_files_stat',
  'get_api_v1_workspaces_wid_files_thumbnail',
  'get_api_v1_workspaces_wid_files_tree',
  'post_api_v1_workspaces_wid_files_upload',
  'post_api_v1_workspaces_wid_uploads',
  'post_api_v1_workspaces_wid_uploads_id_complete',
  'get_api_v1_workspaces_recent',
  'post_auth_login',
  'post_auth_logout',
  'get_auth_me',
  'get_auth_profile_summary',
  'post_auth_refresh',
  'post_oauth_authorize',
  'post_oauth_token',
] as const;

type ExpectedOperationId = (typeof ExpectedRouteOperationIds)[number];
type PolicyProfile =
  | 'tenantRead' | 'tenantAction' | 'collectionQuery' | 'collectionWrite'
  | 'collectionCreate' | 'collectionAccepted' | 'itemRead' | 'itemAction'
  | 'itemCreate' | 'itemAccepted' | 'modelQuota' | 'modelStream' | 'taskCreate'
  | 'taskStop' | 'sessionCreate' | 'sessionAction' | 'sessionTurn' | 'fileWrite'
  | 'fileCreate' | 'streamTicket' | 'unsupported' | 'publicCredential'
  | 'publicRequest' | 'refreshAction';

const tenantErrors = ['RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED', 'PERMISSION_DENIED'] as const satisfies readonly ErrorCode[];
const collectionErrors = ['VALIDATION_FAILED', ...tenantErrors] as const satisfies readonly ErrorCode[];
const itemErrors = [...collectionErrors, 'NOT_FOUND'] as const satisfies readonly ErrorCode[];

const policy = (
  auth: RoutePolicyExpectation['auth'],
  successStatus: number,
  errors: readonly ErrorCode[],
): RoutePolicyExpectation => ({ auth, successStatus, errors });

const PolicyProfiles = {
  tenantRead: policy('access-token', 200, tenantErrors),
  tenantAction: policy('access-token', 200, tenantErrors),
  collectionQuery: policy('access-token', 200, collectionErrors),
  collectionWrite: policy('access-token', 200, collectionErrors),
  collectionCreate: policy('access-token', 201, collectionErrors),
  collectionAccepted: policy('access-token', 202, collectionErrors),
  itemRead: policy('access-token', 200, itemErrors),
  itemAction: policy('access-token', 200, itemErrors),
  itemCreate: policy('access-token', 201, itemErrors),
  itemAccepted: policy('access-token', 202, itemErrors),
  modelQuota: policy('access-token', 200, [...itemErrors, 'QUOTA_EXCEEDED']),
  modelStream: policy('access-token', 202, [...itemErrors, 'QUOTA_EXCEEDED', 'UNSUPPORTED_EVENT_TYPE', 'STREAM_GAP']),
  taskCreate: policy('access-token', 201, [...collectionErrors, 'TASK_LIMIT_EXCEEDED']),
  taskStop: policy('access-token', 200, [...itemErrors, 'NO_RUNNING_TASK_RUN', 'CANCEL_NOT_OWNED', 'CANCEL_FAILED']),
  sessionCreate: policy('access-token', 202, [...collectionErrors, 'SESSION_BUSY', 'IN_PROGRESS']),
  sessionAction: policy('access-token', 200, [...itemErrors, 'SESSION_BUSY', 'IN_PROGRESS']),
  sessionTurn: policy('access-token', 202, [...itemErrors, 'SESSION_BUSY', 'IN_PROGRESS']),
  fileWrite: policy('access-token', 200, [...itemErrors, 'PAYLOAD_TOO_LARGE', 'STORAGE_QUOTA_EXCEEDED']),
  fileCreate: policy('access-token', 201, [...itemErrors, 'PAYLOAD_TOO_LARGE', 'STORAGE_QUOTA_EXCEEDED']),
  streamTicket: policy('access-token', 200, [...itemErrors, 'TICKET_EXPIRED', 'TICKET_ALREADY_USED', 'UNSUPPORTED_EVENT_TYPE', 'STREAM_GAP']),
  unsupported: policy('access-token', 501, ['UNSUPPORTED_FEATURE']),
  publicCredential: policy('public', 200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED']),
  publicRequest: policy('public', 200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR']),
  refreshAction: policy('refresh-cookie', 200, ['RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED']),
} as const satisfies Record<PolicyProfile, RoutePolicyExpectation>;

// Every operation is intentionally assigned. The Record type makes omissions a compile error;
// there is no fallback profile.
export const RoutePolicyAssignments = {
  get_api_v1_agents: 'tenantRead',
  post_api_v1_agents: 'collectionCreate',
  delete_api_v1_agents_id: 'itemAction',
  get_api_v1_agents_id: 'itemRead',
  patch_api_v1_agents_id: 'itemAction',
  get_api_v1_agents_preset_templates: 'tenantRead',
  get_api_v1_agents_presets: 'tenantRead',
  post_api_v1_agents_presets_presetId_install: 'itemAction',
  post_api_v1_artifacts_artifactId_preview: 'itemAction',
  delete_api_v1_artifacts_preview_sessions_previewSessionId: 'itemAction',
  post_api_v1_asr_sessions: 'collectionCreate',
  get_api_v1_billing_account: 'tenantRead',
  post_api_v1_billing_byok: 'collectionWrite',
  delete_api_v1_billing_byok_provider: 'itemAction',
  get_api_v1_billing_plan: 'tenantRead',
  get_api_v1_billing_usage: 'tenantRead',
  get_api_v1_config_app_info: 'tenantRead',
  get_api_v1_config_enterprise: 'tenantRead',
  get_api_v1_cowork_bootstrap: 'tenantRead',
  put_api_v1_cowork_bootstrap: 'collectionWrite',
  get_api_v1_cowork_config: 'tenantRead',
  patch_api_v1_cowork_config: 'collectionWrite',
  get_api_v1_cowork_dreaming_diary: 'tenantRead',
  get_api_v1_cowork_dreaming_status: 'tenantRead',
  get_api_v1_cowork_memory_entries: 'tenantRead',
  post_api_v1_cowork_memory_entries: 'collectionWrite',
  delete_api_v1_cowork_memory_entries_id: 'itemAction',
  patch_api_v1_cowork_memory_entries_id: 'itemAction',
  get_api_v1_cowork_memory_stats: 'tenantRead',
  get_api_v1_html_shares: 'collectionQuery',
  post_api_v1_html_shares: 'collectionCreate',
  get_api_v1_html_shares_id: 'itemRead',
  put_api_v1_html_shares_id: 'itemAction',
  patch_api_v1_html_shares_id_access_mode: 'itemAction',
  patch_api_v1_html_shares_id_status: 'itemAction',
  get_api_v1_html_shares_shareId_deployment: 'itemRead',
  delete_api_v1_kits_id: 'itemAction',
  post_api_v1_kits_install: 'collectionCreate',
  get_api_v1_kits_installed: 'tenantRead',
  get_api_v1_kits_marketplace: 'tenantRead',
  delete_api_v1_kv_key: 'itemAction',
  get_api_v1_kv_key: 'itemRead',
  put_api_v1_kv_key: 'itemAction',
  get_api_v1_mcp_marketplace: 'tenantRead',
  get_api_v1_mcp_servers: 'tenantRead',
  post_api_v1_mcp_servers: 'collectionCreate',
  delete_api_v1_mcp_servers_id: 'itemAction',
  patch_api_v1_mcp_servers_id: 'itemAction',
  post_api_v1_mcp_servers_id_launch_resolution_retry: 'itemAction',
  get_api_v1_media_tasks_taskId: 'itemRead',
  post_api_v1_media_tasks_taskId_cancel: 'itemAction',
  get_api_v1_model_config: 'tenantRead',
  put_api_v1_model_config: 'collectionWrite',
  post_api_v1_model_config_check: 'collectionWrite',
  post_api_v1_model_proxy: 'modelQuota',
  post_api_v1_model_stream: 'modelStream',
  post_api_v1_model_stream_requestId_abort: 'itemAction',
  get_api_v1_models: 'tenantRead',
  get_api_v1_models_id: 'itemRead',
  get_api_v1_plugins: 'tenantRead',
  delete_api_v1_plugins_id: 'itemAction',
  patch_api_v1_plugins_id: 'itemAction',
  put_api_v1_plugins_id_config: 'itemAction',
  get_api_v1_plugins_id_config_schema: 'itemRead',
  post_api_v1_plugins_id_update: 'itemAction',
  post_api_v1_plugins_batch_save: 'collectionWrite',
  post_api_v1_plugins_detect: 'collectionWrite',
  post_api_v1_plugins_install: 'collectionWrite',
  post_api_v1_plugins_sync: 'collectionWrite',
  get_api_v1_plugins_updates_check: 'tenantRead',
  get_api_v1_pricing_models: 'tenantRead',
  post_api_v1_privacy_deletions: 'collectionAccepted',
  get_api_v1_privacy_deletions_deletionId: 'itemRead',
  post_api_v1_privacy_exports: 'collectionAccepted',
  get_api_v1_privacy_exports_exportId: 'itemRead',
  post_api_v1_runtime_migration_backups: 'collectionWrite',
  get_api_v1_runtime_migration_last_restore: 'tenantRead',
  post_api_v1_runtime_migration_restores: 'collectionWrite',
  post_api_v1_runtime_provision: 'collectionAccepted',
  post_api_v1_runtime_repair: 'collectionAccepted',
  post_api_v1_runtime_restart: 'collectionAccepted',
  get_api_v1_runtime_session_policy: 'tenantRead',
  put_api_v1_runtime_session_policy: 'collectionWrite',
  get_api_v1_runtime_status: 'tenantRead',
  get_api_v1_scheduled_tasks: 'tenantRead',
  post_api_v1_scheduled_tasks: 'taskCreate',
  delete_api_v1_scheduled_tasks_id: 'itemAction',
  get_api_v1_scheduled_tasks_id: 'itemRead',
  patch_api_v1_scheduled_tasks_id: 'itemAction',
  get_api_v1_scheduled_tasks_id_runs: 'itemRead',
  post_api_v1_scheduled_tasks_id_runs: 'itemAction',
  get_api_v1_scheduled_tasks_id_runs_count: 'itemRead',
  post_api_v1_scheduled_tasks_id_stop: 'taskStop',
  get_api_v1_scheduled_tasks_channels: 'tenantRead',
  get_api_v1_scheduled_tasks_channels_ch_conversations: 'itemRead',
  get_api_v1_scheduled_tasks_runs: 'collectionQuery',
  get_api_v1_scheduled_tasks_runs_runId_session: 'itemRead',
  get_api_v1_sessions: 'collectionQuery',
  post_api_v1_sessions: 'sessionCreate',
  delete_api_v1_sessions_id: 'itemAction',
  get_api_v1_sessions_id: 'itemRead',
  patch_api_v1_sessions_id: 'itemAction',
  post_api_v1_sessions_id_compact_context: 'sessionAction',
  get_api_v1_sessions_id_context_usage: 'itemRead',
  post_api_v1_sessions_id_exports_result_image: 'itemAction',
  post_api_v1_sessions_id_exports_text: 'itemAction',
  post_api_v1_sessions_id_fork: 'sessionAction',
  get_api_v1_sessions_id_managed: 'itemRead',
  get_api_v1_sessions_id_messages: 'itemRead',
  post_api_v1_sessions_id_permissions_requestId_respond: 'itemAction',
  get_api_v1_sessions_id_rail_index: 'itemRead',
  post_api_v1_sessions_id_result_image_chunks: 'itemAction',
  post_api_v1_sessions_id_result_image_files: 'fileWrite',
  patch_api_v1_sessions_id_runtime: 'itemAction',
  post_api_v1_sessions_id_stop: 'sessionAction',
  get_api_v1_sessions_id_subagents: 'itemRead',
  post_api_v1_sessions_id_title_generation: 'itemAction',
  post_api_v1_sessions_id_turns: 'sessionTurn',
  post_api_v1_sessions_id_viewed: 'itemAction',
  post_api_v1_sessions_batch_delete: 'collectionWrite',
  get_api_v1_share_deployments_deploymentId: 'itemRead',
  post_api_v1_share_deployments_analyze: 'collectionWrite',
  post_api_v1_share_deployments_candidates: 'collectionWrite',
  post_api_v1_share_deployments_node: 'unsupported',
  post_api_v1_share_deployments_static: 'collectionWrite',
  get_api_v1_skills: 'tenantRead',
  delete_api_v1_skills_id: 'itemAction',
  patch_api_v1_skills_id: 'itemAction',
  get_api_v1_skills_id_config: 'itemRead',
  put_api_v1_skills_id_config: 'itemAction',
  post_api_v1_skills_id_confirm: 'itemAction',
  post_api_v1_skills_id_test: 'itemAction',
  post_api_v1_skills_id_upgrade: 'itemAction',
  post_api_v1_skills_install: 'collectionCreate',
  get_api_v1_skills_marketplace: 'tenantRead',
  get_api_v1_skills_routing_prompt: 'tenantRead',
  post_api_v1_skills_sync: 'collectionWrite',
  post_api_v1_stream_ticket: 'streamTicket',
  delete_api_v1_subagents_runId: 'itemAction',
  get_api_v1_subagents_runId_messages: 'itemRead',
  get_api_v1_workspaces: 'tenantRead',
  post_api_v1_workspaces: 'collectionWrite',
  delete_api_v1_workspaces_wid_files: 'itemAction',
  get_api_v1_workspaces_wid_files_download: 'itemRead',
  get_api_v1_workspaces_wid_files_stat: 'itemRead',
  get_api_v1_workspaces_wid_files_thumbnail: 'itemRead',
  get_api_v1_workspaces_wid_files_tree: 'itemRead',
  post_api_v1_workspaces_wid_files_upload: 'fileWrite',
  post_api_v1_workspaces_wid_uploads: 'fileCreate',
  post_api_v1_workspaces_wid_uploads_id_complete: 'fileWrite',
  get_api_v1_workspaces_recent: 'tenantRead',
  post_auth_login: 'publicCredential',
  post_auth_logout: 'refreshAction',
  get_auth_me: 'tenantRead',
  get_auth_profile_summary: 'tenantRead',
  post_auth_refresh: 'refreshAction',
  post_oauth_authorize: 'publicRequest',
  post_oauth_token: 'publicCredential',
} as const satisfies Record<ExpectedOperationId, PolicyProfile>;

export const RoutePolicyExpectations = Object.fromEntries(
  Object.entries(RoutePolicyAssignments).map(([operationId, profile]) => [operationId, PolicyProfiles[profile]]),
) as Record<ExpectedOperationId, RoutePolicyExpectation>;
