import type { ErrorCode } from '../errors.js';

export interface RoutePolicyExpectation {
  readonly auth: 'public' | 'access-token' | 'refresh-cookie';
  readonly successStatus: number;
  readonly errors: readonly ErrorCode[];
}

// This independent operation list is intentionally not imported from RouteRegistry. A route
// addition, removal, or rename must update the reviewed policy denominator explicitly.
export const ExpectedRouteOperationIds = [
  'get_api_v1_agents',
  'post_api_v1_agents',
  'delete_api_v1_agents_id',
  'get_api_v1_agents_id',
  'patch_api_v1_agents_id',
  'get_api_v1_agents_preset_templates',
  'get_api_v1_agents_presets',
  'post_api_v1_agents_presets_presetId_install',
  'post_api_v1_artifacts_artifactId_preview',
  'delete_api_v1_artifacts_preview_sessions_previewSessionId',
  'post_api_v1_asr_sessions',
  'get_api_v1_billing_account',
  'post_api_v1_billing_byok',
  'delete_api_v1_billing_byok_provider',
  'get_api_v1_billing_plan',
  'get_api_v1_billing_usage',
  'get_api_v1_config_app_info',
  'get_api_v1_config_enterprise',
  'get_api_v1_cowork_bootstrap',
  'put_api_v1_cowork_bootstrap',
  'get_api_v1_cowork_config',
  'patch_api_v1_cowork_config',
  'get_api_v1_cowork_dreaming_diary',
  'get_api_v1_cowork_dreaming_status',
  'get_api_v1_cowork_memory_entries',
  'post_api_v1_cowork_memory_entries',
  'delete_api_v1_cowork_memory_entries_id',
  'patch_api_v1_cowork_memory_entries_id',
  'get_api_v1_cowork_memory_stats',
  'get_api_v1_html_shares',
  'post_api_v1_html_shares',
  'get_api_v1_html_shares_id',
  'put_api_v1_html_shares_id',
  'patch_api_v1_html_shares_id_access_mode',
  'patch_api_v1_html_shares_id_status',
  'get_api_v1_html_shares_shareId_deployment',
  'delete_api_v1_kits_id',
  'post_api_v1_kits_install',
  'get_api_v1_kits_installed',
  'get_api_v1_kits_marketplace',
  'delete_api_v1_kv_key',
  'get_api_v1_kv_key',
  'put_api_v1_kv_key',
  'get_api_v1_mcp_marketplace',
  'get_api_v1_mcp_servers',
  'post_api_v1_mcp_servers',
  'delete_api_v1_mcp_servers_id',
  'patch_api_v1_mcp_servers_id',
  'post_api_v1_mcp_servers_id_launch_resolution_retry',
  'get_api_v1_media_tasks_taskId',
  'post_api_v1_media_tasks_taskId_cancel',
  'get_api_v1_model_config',
  'put_api_v1_model_config',
  'post_api_v1_model_config_check',
  'post_api_v1_model_proxy',
  'post_api_v1_model_stream',
  'post_api_v1_model_stream_requestId_abort',
  'get_api_v1_models',
  'get_api_v1_models_id',
  'get_api_v1_plugins',
  'delete_api_v1_plugins_id',
  'patch_api_v1_plugins_id',
  'put_api_v1_plugins_id_config',
  'get_api_v1_plugins_id_config_schema',
  'post_api_v1_plugins_id_update',
  'post_api_v1_plugins_batch_save',
  'post_api_v1_plugins_detect',
  'post_api_v1_plugins_install',
  'post_api_v1_plugins_sync',
  'get_api_v1_plugins_updates_check',
  'get_api_v1_pricing_models',
  'post_api_v1_privacy_deletions',
  'get_api_v1_privacy_deletions_deletionId',
  'post_api_v1_privacy_exports',
  'get_api_v1_privacy_exports_exportId',
  'post_api_v1_runtime_migration_backups',
  'get_api_v1_runtime_migration_last_restore',
  'post_api_v1_runtime_migration_restores',
  'post_api_v1_runtime_provision',
  'post_api_v1_runtime_repair',
  'post_api_v1_runtime_restart',
  'get_api_v1_runtime_session_policy',
  'put_api_v1_runtime_session_policy',
  'get_api_v1_runtime_status',
  'get_api_v1_scheduled_tasks',
  'post_api_v1_scheduled_tasks',
  'delete_api_v1_scheduled_tasks_id',
  'get_api_v1_scheduled_tasks_id',
  'patch_api_v1_scheduled_tasks_id',
  'get_api_v1_scheduled_tasks_id_runs',
  'post_api_v1_scheduled_tasks_id_runs',
  'get_api_v1_scheduled_tasks_id_runs_count',
  'post_api_v1_scheduled_tasks_id_stop',
  'get_api_v1_scheduled_tasks_channels',
  'get_api_v1_scheduled_tasks_channels_ch_conversations',
  'get_api_v1_scheduled_tasks_runs',
  'get_api_v1_scheduled_tasks_runs_runId_session',
  'get_api_v1_sessions',
  'post_api_v1_sessions',
  'delete_api_v1_sessions_id',
  'get_api_v1_sessions_id',
  'patch_api_v1_sessions_id',
  'post_api_v1_sessions_id_compact_context',
  'get_api_v1_sessions_id_context_usage',
  'post_api_v1_sessions_id_exports_result_image',
  'post_api_v1_sessions_id_exports_text',
  'post_api_v1_sessions_id_fork',
  'get_api_v1_sessions_id_managed',
  'get_api_v1_sessions_id_messages',
  'post_api_v1_sessions_id_permissions_requestId_respond',
  'get_api_v1_sessions_id_rail_index',
  'post_api_v1_sessions_id_result_image_chunks',
  'post_api_v1_sessions_id_result_image_files',
  'patch_api_v1_sessions_id_runtime',
  'post_api_v1_sessions_id_stop',
  'get_api_v1_sessions_id_subagents',
  'post_api_v1_sessions_id_title_generation',
  'post_api_v1_sessions_id_turns',
  'post_api_v1_sessions_id_viewed',
  'post_api_v1_sessions_batch_delete',
  'get_api_v1_share_deployments_deploymentId',
  'post_api_v1_share_deployments_analyze',
  'post_api_v1_share_deployments_candidates',
  'post_api_v1_share_deployments_node',
  'post_api_v1_share_deployments_static',
  'get_api_v1_skills',
  'delete_api_v1_skills_id',
  'patch_api_v1_skills_id',
  'get_api_v1_skills_id_config',
  'put_api_v1_skills_id_config',
  'post_api_v1_skills_id_confirm',
  'post_api_v1_skills_id_test',
  'post_api_v1_skills_id_upgrade',
  'post_api_v1_skills_install',
  'get_api_v1_skills_marketplace',
  'get_api_v1_skills_routing_prompt',
  'post_api_v1_skills_sync',
  'post_api_v1_stream_ticket',
  'delete_api_v1_subagents_runId',
  'get_api_v1_subagents_runId_messages',
  'get_api_v1_workspaces',
  'post_api_v1_workspaces',
  'delete_api_v1_workspaces_wid_files',
  'get_api_v1_workspaces_wid_files_download',
  'get_api_v1_workspaces_wid_files_stat',
  'get_api_v1_workspaces_wid_files_thumbnail',
  'get_api_v1_workspaces_wid_files_tree',
  'post_api_v1_workspaces_wid_files_upload',
  'post_api_v1_workspaces_wid_uploads',
  'post_api_v1_workspaces_wid_uploads_id_complete',
  'get_api_v1_workspaces_recent',
  'post_auth_login',
  'post_auth_logout',
  'get_auth_me',
  'get_auth_profile_summary',
  'post_auth_refresh',
  'post_oauth_authorize',
  'post_oauth_token',
] as const;

type ExpectedOperationId = (typeof ExpectedRouteOperationIds)[number];

const protectedItem: RoutePolicyExpectation = {
  auth: 'access-token',
  successStatus: 200,
  errors: ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED', 'PERMISSION_DENIED', 'NOT_FOUND'],
};

const override = (
  successStatus: number,
  errors: readonly ErrorCode[],
  auth: RoutePolicyExpectation['auth'] = 'access-token',
): RoutePolicyExpectation => ({ auth, successStatus, errors });

const overrides: Partial<Record<ExpectedOperationId, RoutePolicyExpectation>> = {
  post_api_v1_agents: override(201, protectedItem.errors),
  post_api_v1_asr_sessions: override(201, protectedItem.errors),
  post_api_v1_html_shares: override(201, protectedItem.errors),
  post_api_v1_kits_install: override(201, protectedItem.errors),
  post_api_v1_mcp_servers: override(201, protectedItem.errors),
  post_api_v1_skills_install: override(201, protectedItem.errors),
  get_api_v1_billing_account: override(200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED', 'PERMISSION_DENIED']),
  post_api_v1_billing_byok: override(200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED', 'PERMISSION_DENIED']),
  get_api_v1_scheduled_tasks: override(200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED', 'PERMISSION_DENIED']),
  get_api_v1_sessions: override(200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED', 'PERMISSION_DENIED']),
  post_api_v1_model_proxy: override(200, [...protectedItem.errors, 'QUOTA_EXCEEDED']),
  post_api_v1_model_stream: override(202, [...protectedItem.errors, 'QUOTA_EXCEEDED', 'UNSUPPORTED_EVENT_TYPE', 'STREAM_GAP']),
  post_api_v1_privacy_deletions: override(202, protectedItem.errors),
  post_api_v1_privacy_exports: override(202, protectedItem.errors),
  post_api_v1_runtime_provision: override(202, protectedItem.errors),
  post_api_v1_runtime_repair: override(202, protectedItem.errors),
  post_api_v1_runtime_restart: override(202, protectedItem.errors),
  post_api_v1_scheduled_tasks: override(201, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED', 'PERMISSION_DENIED', 'TASK_LIMIT_EXCEEDED']),
  post_api_v1_scheduled_tasks_id_stop: override(200, [...protectedItem.errors, 'NO_RUNNING_TASK_RUN', 'CANCEL_NOT_OWNED', 'CANCEL_FAILED']),
  post_api_v1_sessions: override(202, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED', 'PERMISSION_DENIED', 'SESSION_BUSY', 'IN_PROGRESS']),
  post_api_v1_sessions_id_compact_context: override(200, [...protectedItem.errors, 'SESSION_BUSY', 'IN_PROGRESS']),
  post_api_v1_sessions_id_fork: override(200, [...protectedItem.errors, 'SESSION_BUSY', 'IN_PROGRESS']),
  post_api_v1_sessions_id_stop: override(200, [...protectedItem.errors, 'SESSION_BUSY', 'IN_PROGRESS']),
  post_api_v1_sessions_id_result_image_files: override(200, [...protectedItem.errors, 'PAYLOAD_TOO_LARGE', 'STORAGE_QUOTA_EXCEEDED']),
  post_api_v1_workspaces_wid_files_upload: override(200, [...protectedItem.errors, 'PAYLOAD_TOO_LARGE', 'STORAGE_QUOTA_EXCEEDED']),
  post_api_v1_workspaces_wid_uploads_id_complete: override(200, [...protectedItem.errors, 'PAYLOAD_TOO_LARGE', 'STORAGE_QUOTA_EXCEEDED']),
  post_api_v1_sessions_id_turns: override(202, [...protectedItem.errors, 'SESSION_BUSY', 'IN_PROGRESS']),
  post_api_v1_share_deployments_node: override(501, ['UNSUPPORTED_FEATURE']),
  post_api_v1_stream_ticket: override(200, [...protectedItem.errors, 'TICKET_EXPIRED', 'TICKET_ALREADY_USED', 'UNSUPPORTED_EVENT_TYPE', 'STREAM_GAP']),
  post_api_v1_workspaces_wid_uploads: override(201, [...protectedItem.errors, 'PAYLOAD_TOO_LARGE', 'STORAGE_QUOTA_EXCEEDED']),
  post_auth_login: override(200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED'], 'public'),
  post_oauth_token: override(200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED'], 'public'),
  post_auth_logout: override(200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED'], 'refresh-cookie'),
  post_auth_refresh: override(200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR', 'UNAUTHENTICATED'], 'refresh-cookie'),
  post_oauth_authorize: override(200, ['VALIDATION_FAILED', 'RATE_LIMITED', 'INTERNAL_ERROR'], 'public'),
};

export const RoutePolicyExpectations = Object.fromEntries(
  ExpectedRouteOperationIds.map((operationId) => [operationId, overrides[operationId] ?? protectedItem]),
) as Record<ExpectedOperationId, RoutePolicyExpectation>;
